### ISSUE TITLE
Always remove repos directory in the target directory before generating image

### ISSUE THREAD

**Issue by goldmann** [concrt/concreate#151]
At the generation/sync time we only copy/remove/add repo files that are mentioned in the image descriptor. If there are any changes to repo files, some of these may be left untouched (not removed from the repository). At the same time, when we generate the Dockerfile - **we add all repo files** found in the `repos` directory **but remove only** files that are listed in the image descriptor.

This can lead to builds with repo files not being removed.

Downstream ticket: https://issues.jboss.org/browse/CLOUD-2208

**Comment by dbecvarik** [comment]
I cant reproduce it.

**Comment by goldmann** [comment]
Are we able to write a test for it?

**Comment by dbecvarik** [comment]
yes, we can reuse/update your from eap and have it as validation test.

**Comment by dbecvarik** [comment]
We now use only properly configured repos, so this is probably even not relelevant any more
