### ISSUE TITLE
The 'release' property in image descriptor doesn't appear to do anything

### ISSUE THREAD

**Issue by grdryn** [concrt/concreate#184]
There's an optional 'release' property in the image descriptor: https://github.com/concrt/concreate/blob/develop/concreate/descriptor/image.py#L13

It doesn't appear to be documented, but I'd expect that to work the same as the 'name' and 'version' keys -- populate the 'release' label, but it doesn't appear to do that currently (does it do anything?).

**Comment by goldmann** [comment]
Good catch :) It was used some time ago and is now a leftover, not used anymore. For releases, you should tag the repository. We do not advice to use release. Currently we do not have a use case for it.

While executing a build in OSBS, the release number is handled by the system. This means that we have no idea what ill be the release in the upstream code. Additionally it does not make sense to update it over and over to do another build. We tag it once (the repo itself), after the correct build is done.

Does it explain it?

**Comment by grdryn** [comment]
I think so, thanks for the info! To clarify, are you saying that if we omit the release label altogether from a Dockerfile, OSBS will just increment it from the previous build, or will it just make it something random?

**Comment by goldmann** [comment]
It will be incremented by 1.

**Comment by grdryn** [comment]
Oh that's great! We've just been doing that manually up to now.

I'll leave it to you to decide what to do with this issue: whether to close it or whatever. Thanks!

**Comment by goldmann** [comment]
I'll close it since it was clarified.
