### ISSUE TITLE
Use Resource objects instead of specialized code

### ISSUE THREAD

**Issue by rcernich** [concrt/concreate#76]
https://github.com/jboss-container-images/concreate/blob/4eb1c03521ff201c41a3e4dd0cee1ebd98160dd7/concreate/builders/osbs.py#L54-L55

Instead of spreading the logic for downloading resources all over the place, I think we can use a custom factory for creating an OsbsResource for these.

**Comment by goldmann** [comment]
FYI The idea was to just copy whatever code we have now and use it with the intention to refactor it later.

**Comment by dbecvarik** [comment]
We should move to tree of object soon - probably with 2.0.

**Comment by dbecvarik** [comment]
it will be fixed by #119

**Comment by dbecvarik** [comment]
was already implemented
